---
- name: add kuvernetes repository
  yum_repository:
    name: Kubernetes
    description: Kubernetes repo
    baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
    enabled: true
    gpgcheck: true
    repo_gpgcheck: true
    gpgkey: https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg

- name: "Installing kubelet, kubeadm and kubectl"
  yum:
    name:
      - kubeadm
      - kubelet
      - kubectl
    state: present
    update_cache: true