---
- name: Add docker repository
  yum_repository:
    name: "docker-ce"
    description: "Docker-ce stable repository"
    baseurl: https://download.docker.com/linux/centos/7/$basearch/stable
    gpgkey: https://download.docker.com/linux/centos/gpg
    gpgcheck: yes
    enabled: yes

- name: "Installing Docker and Prerequisite packages"
  yum:
    name:
      - yum-utils
      - device-mapper-persistent-data
      - lvm2
      - docker-{{docker_version}}
    state: present
    update_cache: true